# Generated by Django 5.0 on 2024-01-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantmodel',
            name='image',
            field=models.ImageField(upload_to='users/images/'),
        ),
    ]
