# Generated by Django 5.0 on 2024-01-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_tution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='appaly_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
    ]
